# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        my_config_1:
            toolbar: "my_toolbar_1"
            uiColor: "#ffffff"
            height: "150"
            width: "95%"
            margin-top: "20px"
            resize_enabled: false
            removePlugins: 'elementspath'

    toolbars:
        configs:
            my_toolbar_1: [ [ "Maximize" ], [ "TextColor" ], ["Bold"], ["Italic"], ["BulletedList"], ["NumberedList"] ]
